### ISSUE TITLE
Variorum 0.2.0 fails to build on Ubuntu Eoan 19.10

### ISSUE THREAD

**Issue by rountree** [LLNL/variorum#51]
In short, `nvml.h` isn't found.  cmake did not toss up an error about a missing dependence.

    rountree@Solvent:~/local/variorum/build$ make
    [  2%] Built target gtest
    Scanning dependencies of target gtest_main
    [  3%] Building CXX object thirdparty_builtin/googletest/CMakeFiles/gtest_main.dir /src/gtest_main.cc.o
    [  4%] Linking CXX static library libgtest_main.a
    [  4%] Built target gtest_main
    [  5%] Building C object variorum/Nvidia/CMakeFiles/variorum_nvidia.dir/Volta.c.o
    In file included from /home/rountree/local/variorum/src/variorum/Nvidia/Volta.c:12:
    /home/rountree/local/variorum/src/variorum/Nvidia/power_features.h:12:10: fatal error: nvml.h: No such file or directory
    12 | #include <nvml.h>
      |          ^~~~~~~~
    compilation terminated.
    make[2]: *** [variorum/Nvidia/CMakeFiles/variorum_nvidia.dir/build.make:63: variorum/Nvidia/CMakeFiles/variorum_nvidia.dir/Volta.c.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:596: variorum/Nvidia/CMakeFiles/variorum_nvidia.dir/all] Error 2 
    make: *** [Makefile:141: all] Error 2

**Comment by rountree** [comment]
> root@Solvent:/home/rountree/local/variorum# apt-get install nvidia-cuda-dev
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  nvidia-cuda-dev : Depends: libcuinj64-10.1 (= 10.1.168-1build1) but it is not going to be installed
>                    Recommends: libnvcuvid1 but it is not installable
> E: Unable to correct problems, you have held broken packages.

**Comment by rountree** [comment]
`hwloc-dev` provides an `nvml.h` file that gets placed in `/usr/include/hwloc` and contains the line:
    #include <nvml.h>
So I still need to find a working ubuntu package that will install the real nvml.h in /usr/include.  I don't think we want to have a dependence on that header when building for x86_64 alone.

**Comment by rountree** [comment]
I think the underlying issue is the default configuration build nvidia.  That can be made a separate, simpler bug report.  Closing this.
